### ISSUE TITLE
No CUDA GPUs Error

### ISSUE THREAD

**Issue by Aniq55** [CGCL-codes/CausalNet#1]
I get a CUDA not found error, while I have checked that CUDA was indeed available

```
This dataset is already preprocessed.
Traceback (most recent call last):
  File "/home/x/Documents/CausalNET/model/main.py", line 447, in <module>
    main(OmegaConf.load(args.opt), device=device)
  File "/home/x/Documents/CausalNET/model/main.py", line 421, in main
    model = CausalNET(num_types, topology, prior_cm, opt.model, log, device=device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/Documents/CausalNET/model/main.py", line 44, in __init__
    ).to(self.device)
      ^^^^^^^^^^^^^^^
  File "/home/x/anaconda3/envs/ml/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/anaconda3/envs/ml/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/x/anaconda3/envs/ml/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/x/anaconda3/envs/ml/lib/python3.11/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/x/anaconda3/envs/ml/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/anaconda3/envs/ml/lib/python3.11/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

I am running the command 
> `python -u main.py -g 1 -task test_M24 -opt ./configs/config_m24.yaml`

**Comment by zhjcp** [comment]
Hello, I am currently not in the lab and cannot access the server with GPUs, so I am unable to perform tests with GPUs. I ran the code on my own computer with CPUs, and it works fine. Based on the error log, it seems that there might be an issue in your environment. I suggest you first test the code using CPUs (don't forget to change Line-141 in Model.py from 'cuda' to 'cpu') to confirm that there are no other issues, and then try testing with GPUs again.
